sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: An3Jl12yG/k7isFMbgbX7RNCH5V0+k68SbzhvyetWJy6D4Jc3vzT4XhCr1nBKUeuIb5ZAtFgKT3HXsFGK7llpN13fqH0bw1oEoHa7bSRX2xr8xfi3pxkonlt1dqB7FaSwBVyd/zyyTysGin4FFFYEaLHEcm0OGrxGxl/s6Vu6dFtrw6taTYPqqQQsrwWTpOiKCzZn7tBSwzgp7XutsX5AzDTIcBRAJ+7RjsLvGybDUZFm2EcuJoUjOQGgWX2DwXp9fVId/s+H7nBfQOl18Ijnun3uz9J+F/74fGr+DAQbXM07dchBpMUUhWOZ6hax6V7RVCtyQA8tSpnqL1RmD1uSRirmTg5CHbomoe2QG8v0GP/C3C8tOVOeksmll/LML1R3YSFj2govnYkj6/PwxRnBN4dF9NwsAFPkYjdYwIAcxRjLkFZIuBCfgFFxosPN7TqTgoig5L5EB8fVYCpI9V+8GlKZSZiGJJ9BsAI9uF3wmWh8atlPRm0PgRg2GgMPOlcHxN/AfNYkG6r2Z144Mbm4aT5fuvd62uVqCCly0Qcwr6lsvqjO2Wk8azohGC+tECh/Ykbsf5WBfE5NzII01m9JotkMrpCX7LrAXaNYQKDLV8CsWAHQRLxr5xwfErVR+MMkCQz4oRQVw9WMAG9AONEGLVqtwKpUGFcw3tABZXyhew=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-First-1000-Euler-Numbers_2584
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy